version: "3.9"
    
services:
  php:
    build: .
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www/html
  db:
    image: mysql:5.7
    container_name: syllabus_projet_docker
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: projetdocker
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
    restart: always
    ports:
      - 8081:80
    depends_on:
      - db
volumes:
  dbdata: {}